---
title: "update_oxyura_jamaicensis_management"
author: "Sander Devisscher"
date: "2024-04-08"
output: html_document
---

```{r libraries}
library(rgbif)
library(dplyr)
library(readr)
library(magrittr)
library(tidyr)
library(stringr)
library(testthat)
library(sf)
```

```{r initiate download}
datasetKey <- c("7522721f-4d97-4984-8231-c9e061ef46df")

down_rst <- occ_download(
  pred("taxonKey", 2498305),
  pred_in("datasetKey", datasetKey),
  format = "DWCA",
  user = Sys.getenv("gbif_user"), 
  pwd = Sys.getenv("gbif_pwd"), 
  email = Sys.getenv("email"))

occ_download_wait(down_rst,
                  curlopts = list(verbose = TRUE,
                                  http_version = 2,
                                  forbid_reuse = TRUE))
# Read occurrence data ####
raw_ruddy_data <- occ_download_get(down_rst) %>%
  occ_download_import()

# Read verbatim data ####
# Needed for lifestage information 
ruddy_zipfile <- dir(path = "./",
               pattern = ".zip")

unzip(zipfile = ruddy_zipfile,
      files = "verbatim.txt",
      exdir = tempdir())

ruddy_verbatim_raw <- read_tsv(paste0(tempdir(), "/verbatim.txt"))
```

```{r cleanup}
if(length(ruddy_zipfile) == 1) {
  unlink(ruddy_zipfile)
  unlink(paste0(tempdir(), "/verbatim.txt"))
}else{
  stop("More than 1 zipfile detected in the root folder, please cleanup!!")
}
```

```{r read old data}
ruddy_old <- read_csv(file = "https://raw.githubusercontent.com/inbo/aspbo/uat/data/output/UAT_direct/Oxyura_jamaicensis.csv")

cols_ruddy_old <- colnames(ruddy_old)

sampling_protocols <- unique(ruddy_old$samplingProtocol) 
```

```{r prep verbatim}
ruddy_verbatim_sex <- ruddy_verbatim_raw %>% 
  select(gbifID, sex) %>% 
  mutate(sex = str_remove(sex, "[{]"),
         sex = str_remove(sex, "[}]"),
         sex = str_remove(sex, " "),
         sex = str_replace_all(sex, "\"", "")) %>% 
  separate(col = sex, 
           sep = ",",
           into = c("sex_1", "sex_2")) %>% 
  pivot_longer(cols = c("sex_1", "sex_2"),
               names_to = NULL) %>% 
  separate(col = value,
           sep = ":",
           into = c("gender", "count")) %>% 
  filter(!is.na(gender))

ruddy_verbatim_age <- ruddy_verbatim_raw %>% 
  select(gbifID, lifeStage) %>% 
  mutate(lifeStage = str_remove(lifeStage, "[{]"),
         lifeStage = str_remove(lifeStage, "[}]"),
         lifeStage = str_remove(lifeStage, " "),
         lifeStage = str_replace_all(lifeStage, "\"", "")) %>% 
  separate(col = lifeStage, 
           sep = ",",
           into = c("age_1", "age_2")) %>% 
  pivot_longer(cols = c("age_1", "age_2"),
               names_to = NULL) %>% 
  separate(col = value,
           sep = ":",
           into = c("age", "count")) %>% 
  filter(!is.na(age)) %>% 
  mutate(count = as.integer(count))

ruddy_adult <- ruddy_verbatim_age %>% 
  filter(age == "adult") %>% 
  group_by(gbifID) %>% 
  summarise(adult = sum(count, na.rm = TRUE))

ruddy_juvenile <- ruddy_verbatim_age %>% 
  filter(age != "adult") %>% 
  rename(gender = age)

ruddy_gender <- rbind(ruddy_verbatim_sex, ruddy_juvenile)

ruddy_verbatim_rework <- ruddy_adult %>% 
  full_join(ruddy_gender, by = "gbifID") %>% 
  mutate(count = as.integer(count))
```

```{r add gemeente, provincie en gewest}
utm10 <- st_read("./data/output/UAT_processing/grid/utm10_bel_with_regions.gpkg", 
                  layer="utm10_bel_with_regions" )

ruddy_sf <- raw_ruddy_data %>% 
  select(gbifID, decimalLatitude, decimalLongitude) %>% 
  st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), crs = 4326) %>% 
  st_transform(crs = st_crs(utm10)) %>% 
  st_join(utm10) %>% 
  mutate(gbifID = as.double(gbifID)) %>%
  select(gbifID, gemeente, provincie, gewest) %>% 
  st_drop_geometry()
```

```{r prep data}
ruddy_data <- raw_ruddy_data %>% 
  filter(samplingProtocol %in% sampling_protocols) %>% 
  mutate(gbifID = as.double(gbifID),
         isFlanders = TRUE,
         isBrussels = FALSE,
         isWallonia = FALSE) %>%
  left_join(ruddy_verbatim_rework, by = "gbifID") %>% 
  left_join(ruddy_sf, by = "gbifID") %>% 
  select(any_of(cols_ruddy_old), gemeente, provincie, gewest) %>% 
  mutate(gbifID = as.character(gbifID))
```

```{r tests}
test_that("columns not present in download", {
  testthat::expect_contains(colnames(ruddy_data), cols_ruddy_old)
})
```

```{r export}
write_csv(ruddy_data, "./data/output/UAT_direct/Oxyura_jamaicensis.csv", quote = "all")
```

