---
title: "get_data_from_gbif"
author: "Sander Devisscher"
date: "`r Sys.Date()`"
output: html_document
---

```{r libraries}
library(rgbif)
library(sf)
library(tidyverse)
```

Data from these datasets can be used to determine the status of the nests in

WALLONIA: DEMNA-DNE : Early warning system on Introduced Species in Wallonia: https://www.gbif.org/dataset/04871911-1b00-41f3-8dc6-fc0cea421f96
BRUSSELS: iNaturalist Research-grade Observations: https://www.gbif.org/dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7

```{r download data from gbif}
taxonkeys <- c(1311477)
datasetkey_wal <- "04871911-1b00-41f3-8dc6-fc0cea421f96"
datasetkey_bxl <- "50c9509d-22c7-4a22-a47d-8c48425ef4a7"

# Initiate brussels download
bxl_downloadKey <- occ_download(pred_in("taxonKey", taxonkeys), # limit download to Vespa velutina
                                pred_in("datasetKey", datasetkey_bxl), # limit download to inaturalist
                                pred_in("level1Gid", "BEL.1_1"), # limit download to BXL
                                user = Sys.getenv("gbif_user"),
                                pwd = Sys.getenv("gbif_pwd"),
                                email = Sys.getenv("email"),
                                curlopts = list(verbose = TRUE,
                                                http_version = 2,
                                                forbid_reuse = TRUE))

# Initiate wallonia download
wal_downloadKey <- occ_download(pred_in("taxonKey", taxonkeys), # limit download to Vespa velutina
                                pred_in("datasetKey", datasetkey_wal), # limit download to DEMNA-DNE
                                pred_in("level1Gid", "BEL.3_1"), # limit download to WALLONIA
                                user = Sys.getenv("gbif_user"),
                                pwd = Sys.getenv("gbif_pwd"),
                                email = Sys.getenv("email"),
                                curlopts = list(verbose = TRUE,
                                                http_version = 2,
                                                forbid_reuse = TRUE))

# Wait for downloads to finish
## BXL
occ_download_wait(bxl_downloadKey,
                  curlopts = list(verbose = TRUE,
                                  http_version = 2,
                                  forbid_reuse = TRUE))

bxl_download <- occ_download_get(bxl_downloadKey,
                                 path = tempdir(),
                                 overwrite = TRUE,
                                 curlopts = list(verbose = TRUE,
                                                 http_version = 2,
                                                 forbid_reuse = TRUE))

bxl_rawdata <- occ_download_import(x = bxl_download) 

bxl_rawdata <- bxl_rawdata %>% 
  mutate(eventDate = as.Date(eventDate, format = "%Y-%m-%dT%H:%M:%S"),
         verbatimEventDate = as.character(verbatimEventDate)) %>% 
  filter(behavior == "nest building" |
           behavior == "visiting occupied nest"|
           grepl("evidenceOfPresence:construction", dynamicProperties)|
           organismRemarks == "Nest"|
           occurrenceRemarks =="found as nest"
  )



summary(bxl_rawdata$eventDate)

## WALLONIA
occ_download_wait(wal_downloadKey,
                  curlopts = list(verbose = TRUE,
                                  http_version = 2,
                                  forbid_reuse = TRUE))

wal_download <- occ_download_get(wal_downloadKey,
                                 path = tempdir(),
                                 overwrite = TRUE,
                                 curlopts = list(verbose = TRUE,
                                                 http_version = 2,
                                                 forbid_reuse = TRUE))

not_valid <- c("not validated", "under validation")
valid <- c("validated on the basis of rules", 
           "validated with document",
           "validated without document")

wal_rawdata <- occ_download_import(x = wal_download) %>% 
  mutate(eventDate = as.Date(eventDate, format = "%Y-%m-%dT%H:%M:%S"),
         verbatimEventDate = as.character(verbatimEventDate)) %>% 
  filter(organismRemarks %in% c("Nest", "Nest (inactive)", "Nest (neutralized)")) %>% # keep only nests
  filter(!identificationVerificationStatus %in% not_valid) # omit invalid records

# Check if there are new verification statuses in the data
# and list those
new_verification_statuses <- wal_rawdata %>% 
  filter(!identificationVerificationStatus %in% valid) %>% 
  distinct(identificationVerificationStatus) %>% 
  pull(identificationVerificationStatus)

testthat::expect_equal(length(new_verification_statuses), 0, 
                       info = paste0("'", paste(new_verification_statuses, collapse = "', '"),"' are new in the data, please check them! And add them to the relevant list"))

summary(wal_rawdata$eventDate)
table(wal_rawdata$level1Gid, useNA = "ifany")
table(wal_rawdata$organismRemarks, useNA = "ifany")
table(wal_rawdata$identificationVerificationStatus, useNA = "ifany")

# combine datasets and export
combined_data <- bind_rows(bxl_rawdata, wal_rawdata) %>% 
  write_csv(file = "./data/input/Vespa_management_gbif_data.csv")
```
