Om dit script te laten lopen moet je een .renviron bestand aanmaken met de 
volgende regels:

email = "<je email adres>"
gbif_user = "<je gbif username>"
gbif_pwd = "<je gbif password>"

Dit bestand deel je met niemand!

```{r libraries}
library(sf)
library(googlesheets4)
library(dplyr)
library(magrittr)
library(tidyr)
library(readr)
library(lubridate)
library(testthat)
library(units)
```

```{r conflicted packages, eval=FALSE}
library(tidylog)
conflicted::conflicts_prefer(tidylog::select)
conflicted::conflicts_prefer(tidylog::filter)
conflicted::conflicts_prefer(tidylog::left_join)
conflicted::conflicts_prefer(tidylog::mutate)
conflicted::conflicts_prefer(tidylog::drop_na)
conflicted::conflicts_prefer(tidylog::mutate_at)
conflicted::conflicts_prefer(tidylog::rename)
conflicted::conflicts_prefer(tidylog::replace_na)
conflicted::conflicts_prefer(tidylog::ungroup)
conflicted::conflicts_prefer(tidylog::group_by)
conflicted::conflicts_prefer(tidylog::full_join)
conflicted::conflicts_prefer(tidylog::summarise)
conflicted::conflicts_prefer(tidylog::pivot_longer)
conflicted::conflicts_prefer(tidylog::distinct)
```

```{r read data}
# data from wallonia & bxl
data_gbif_raw <- read_csv("./data/input/Vespa_management_gbif_data.csv")

# data from vespadb
data_vespadb_raw <- read_csv("./data/input/Vespa_management_vespadb_data.csv")
```

```{r GBIF: data prep}
