---
title: "download_occurrence_cube"
author: "Sander Devisscher"
date: "2024-10-17"
output: html_document
---

A script to download the occurrence cube from the GBIF API.


If the installed version of rgbif is < 3.8.1.1, please update the package. 
```{r update rgbif if needed}
current_rgbif_version <- packageVersion("rgbif")

#convert to numeric
current_rgbif_version <- as.numeric(unlist(strsplit(as.character(current_rgbif_version), split = "\\.")))

if(current_rgbif_version[1] < 3 | current_rgbif_version[2] < 8 | current_rgbif_version[3] < 1){
  install.packages("rgbif", dependencies = TRUE)
}
```

```{r libraries}
library(rgbif)
library(tidyverse)
```

```{r get griis checklist}
# Get the griis checklist
griis_checklist <- read_delim("data/output/UAT_processing/data_input_checklist_indicators.tsv", 
                              delim = "\t", escape_double = FALSE, 
                              trim_ws = TRUE) %>% 
  distinct(nubKey, rank)

# Split into dataframes based on rank
griis_checklist_split <- split(griis_checklist, griis_checklist$rank)
```

```{r download rank cubes}
# extract ranks list
ranks <- unique(griis_checklist$rank)

# loop over ranks
for(rank in ranks){
  
  # print rank
  print(rank)
  
  # get nubKeys for the rank
  nubKey_list <- griis_checklist_split[[rank]]$nubKey
  
  # get query file
  query_file <- paste0("data/input/griis_belgium_", tolower(rank), ".txt")
  if(file.exists(query_file)){
    query <- gsub(pattern = "  ", replacement = "", paste0(readLines(query_file), collapse = " "))
  }else{
    warning(paste0(rank, " query file does not exist"))
    next #for testing purposes
  }
  
  # add nubkeys to query
  query <- gsub(pattern = "<--nubkeys-->", replacement = paste0(nubKey_list, " ", collapse = ","), query)
  
  # download occurrence cube
  occ_downloadKey <- occ_download_sql(query,
                                      user = Sys.getenv("gbif_user"),
                                      pwd = Sys.getenv("gbif_pwd"),
                                      email = Sys.getenv("email"),
                                      curlopts = list(verbose = TRUE,
                                                      http_version = 2,
                                                      forbid_reuse = TRUE))
}
```

