```{r setup, include=FALSE}
library(sf)
library(dplyr)
library(readr)
library(stringr)
library(tidyr)
library(uuid)
```

```{r download data, include=FALSE}
rawData <- read_csv("https://raw.githubusercontent.com/inbo/sk-analyse/refs/heads/main/interim/afvangsten_per_fuik_combined.csv")

export_template <- read_csv("https://raw.githubusercontent.com/inbo/aspbo/refs/heads/uat/data/output/UAT_direct/Lithobates_catesbeianus.csv")
```

```{r select necessary columns}
cleanData <- rawData %>% 
  pivot_longer(cols = c("larven_fuik", "juveniel_fuik", "adult_fuik"),
               names_to = "lifeStage",
               values_to = "n") %>% 
  mutate(lifeStage = str_remove(lifeStage, "_fuik")) %>% 
  mutate(lifeStage = case_match(lifeStage,
                                "larven" ~ "larvae",
                                "juveniel" ~ "juvenile",
                                "adult" ~ "adult",
                                .default = NA_character_)) %>% 
  filter(!is.na(n), 
         !is.na(long_vijver)) %>% 
  group_by(eventID, locationID, Locatie, long_vijver, lat_vijver, lifeStage, Jaar) %>% 
  summarise(n = sum(n, na.rm = TRUE),
            no_fuiken = max(no_fuiken, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(gbifID = row_number())

localities <- cleanData %>% 
  distinct(locationID, Locatie, long_vijver, lat_vijver) %>% 
  st_as_sf(coords = c("long_vijver", "lat_vijver"), crs = 4326) %>% 
  st_intersection(st_read("https://raw.githubusercontent.com/inbo/sk-analyse/main/input/Gemeentes.geojson") %>% 
                    select(NISCODE, gemeente = NAAM)) %>% 
  st_intersection(st_read("https://raw.githubusercontent.com/inbo/sk-analyse/main/input/provinces.geojson") %>% 
                    st_transform(4326) %>% 
                    select(provincie = NAAM)) %>% 
  as.data.frame() %>% 
  select(-geometry)

cleanData <- cleanData %>%
  left_join(localities, by = c("locationID", "Locatie")) %>% 
  mutate(gemeente = case_match(gemeente,
                               "Heist-op-den-Berg" ~ "Heist-Op-Den-Berg",
                               .default = gemeente)) %>% 
  mutate(gewest = "flanders")
  
  
fistools::col_content_compare(cleanData, "lifeStage", export_template, "lifeStage")
fistools::col_content_compare(cleanData, "gemeente", export_template, "gemeente")
fistools::col_content_compare(cleanData, "provincie", export_template, "provincie")
fistools::col_content_compare(cleanData, "gewest", export_template, "gewest")

cleanData <- cleanData %>%
  mutate(year = Jaar) %>% 
  mutate(NISCODE = as.integer(NISCODE)) %>% 
  dplyr::select(gbifID,
                year,
                individualCount = n,
                lifeStage,
                eventID,
                locationID,
                NISCODE, 
                gemeente,
                provincie, 
                verbatimLocality = Locatie,
                locality = Locatie,
                n_fuiken = no_fuiken,
                gewest)

jaar_missing <- cleanData %>% 
  filter(is.na(year)) %>% 
  write_csv("./data/interim/Lithobates_catesbeianus_jaar_missing.csv")
  
cleanData <- cleanData %>% 
  filter(!is.na(year))

table(cleanData$year, useNA = "ifany")
table(cleanData$eventID, useNA = "ifany")

vangst_per_year <- cleanData %>% 
  group_by(year) %>% 
  summarise(n = sum(individualCount, na.rm = TRUE))

vangst_per_year
```

```{r export cleanData}
write_csv(cleanData, "./data/output/UAT_direct/Lithobates_catesbeianus.csv")
```
