---
title: "update_trendOccupancy"
author: "Sander Devisscher"
date: "2025-07-30"
output: html_document
---

Trendoccupancy or the evolution of union concern species according to the 
National secretariat of invasive alien species (NSIAS) to the European Union 
via the EASIN reporting tool. 
This evolution consists the number of 10x10km squares infected by a species at 
the moment of inclusion onto the list (t0) compared to the status at the moment of 
a 6y reporting cycle (tx).

```{r libraries}
library(dplyr)
library(magrittr)
library(sf)
```

```{r download zenodo files}
t0_url <- "https://zenodo.org/api/records/7708520/files-archive"
t0_files <- c("ias_belgium_t0_2016.geojson", 
              "ias_belgium_t0_2018.geojson", 
              "ias_belgium_t0_2020.geojson", 
              "ias_belgium_t0_2023.geojson")
t1_url <- "https://zenodo.org/api/records/3060173/files-archive"
t1_files <- c("T1_Belgium_Union_List_Species.shp")
t2_url <- ""

tx <- c("t0", "t1")

for(x in tx){
  destfile <- paste0(tempdir(), "/", x, ".zip")
  url <- get(paste0(x, "_url"))
  tx_files <- get(paste0(x, "_files"))
  exdir <- paste0(tempdir(), "/", x, "/")
  
  download.file(url, destfile, mode = "wb")
  unzip(destfile, exdir = exdir)
  
  tx_file <- data.frame()
  
  for(f in tx_files){
    temp <- sf::st_read(paste0(exdir, f))
    
    if("REFERENCE_" %in% colnames(temp)){
      temp <- temp %>% 
        rename("Reference" = "REFERENCE_")
    }
    
    if("REFERENCE" %in% colnames(temp)){
      temp <- temp %>% 
        rename("Reference" = "REFERENCE")
    }
    
    if("DATA_PARTN" %in% colnames(temp)){
      temp <- temp %>% 
        rename("Data_Partn" = "DATA_PARTN")
    }
    
    if("CellCode" %in% colnames(temp)){
       temp <- temp %>% 
        rename("Cellcode" = "CellCode")
    }
    
    if(nrow(tx_file) == 0){
      tx_file <- temp
    }else{
      tx_file <- rbind(tx_file, temp)
    }
  }
  
  if("species" %in% colnames(tx_file)){
    tx_file <- tx_file %>% 
      rename("Species" = "species")
  }
  
  assign(paste0(x, "_raw"), tx_file)
}
```

```{r set creds}
Sys.setenv("AWS_DEFAULT_REGION" = "eu-west-1")

if(Sys.getenv("S3_BUCKET") != ""){
  UAT_bucket <- Sys.getenv("S3_BUCKET")
}else{
  UAT_bucket <- Sys.getenv("UAT_bucket")
}
```

```{r connect to the bucket}
if(Sys.getenv("amiabot") != "yes"){
  print("Executor of the script is a human >> connecting to bucket")
  source("./src/connect_to_bucket.R")
  connect_to_bucket(bucket_name = UAT_bucket)
}
```

```{r get keys}
keys <- alienSpecies::loadMetaData(type = "keys")
```

```{r check & correct species}

```

```{r export files}

```

