---
title: "build_queries"
author: "Sander Devisscher"
date: "2024-10-17"
---

A script to download the occurrence cube from the GBIF API.

```{r libraries}
library(readr)
library(magrittr)
library(dplyr)
library(rgbif)
```

```{r get griis checklist}
# Get the griis checklist
griis_checklist <- read_delim("data/output/UAT_processing/data_input_checklist_indicators.tsv", 
                              delim = "\t", escape_double = FALSE, 
                              trim_ws = TRUE) %>% 
  distinct(nubKey, rank, classKey)
```

```{r complete col_info}
# Read old col_info
col_info_old <- read_csv("./data/interim/gbif_col_translation.csv") |> 
  filter(FALSE)

# Extract keys not yet on old col_info
to_translate_keys <- griis_checklist |> 
  filter(!nubKey %in% col_info_old$nubKey) |> 
  pull(nubKey)

# If at least 1 key needs translating
if(length(to_translate_keys) > 0){
  
  col_info_new <- data.frame() |> 
    mutate(nubKey = NA_integer_,
           classKey = NA_integer_,
           col_taxon_key = NA_character_,
           col_class_key = NA_character_)
  
  # Translate the key
  for(t in to_translate_keys){
    classKey <- griis_checklist |> 
      filter(nubKey == t) |> 
      pull(classKey)
    
    col_data <- rgbif::gbif_to_col(key = t)
    
    col_taxon_key <- col_data$usage$key
    
    col_class_key <- col_data$classification |> 
      as.data.frame() 
    
    if("key.7" %in% colnames(col_class_key)){
      col_class_key <- col_class_key |> 
        select(class_key = key.7) |> 
        pull()
    }else{
      warning(paste0("No class info found for ", t))
      col_class_key <- NA_character_
    }
    
    
    col_info_new <- col_info_new |> 
      add_row(nubKey = t,
              classKey = classKey,
              col_taxon_key = col_taxon_key,
              col_class_key = col_class_key)
  }
  col_info_combined <- bind_rows(col_info_old, col_info_new)
}else{
  cat("All keys are translated")
  col_info_combined <- col_info_old
}

col_info_missing <- col_info_combined |> 
  filter(is.na(col_taxon_key)) |> 
  write_csv("./data/interim/gbif_col_translation_missing.csv")

col_info_combined <- col_info_combined |> 
  filter(!is.na(col_taxon_key)) |> 
  write_csv("./data/interim/gbif_col_translation.csv")
```

```{r}
griis_checklist <- griis_checklist |> 
  left_join(col_info_combined, by = "nubKey") 
```

```{r split griis_checklist}
# Split into dataframes based on rank
griis_checklist_split <- split(griis_checklist, griis_checklist$rank)
```

```{r download rank cubes}
# extract ranks list
ranks <- unique(griis_checklist$rank)

# Combine form, subspecies en variety
ranks <- ranks[!ranks %in% c("FORM", "SUBSPECIES", "VARIETY")]
ranks <- c(ranks, "SUBSPECIES_FORM_VARIETY")

# loop over ranks
for(rank in ranks){
  
  # print rank
  print(rank)
  
  # get nubKeys for the rank
  if(rank == "SUBSPECIES_FORM_VARIETY"){
    nubKey_list <- c(griis_checklist_split[["SUBSPECIES"]]$col_taxon_key,
                     griis_checklist_split[["FORM"]]$col_taxon_key,
                     griis_checklist_split[["VARIETY"]]$col_taxon_key)
  }else{
    nubKey_list <- griis_checklist_split[[rank]]$col_taxon_key
  }
  
  # get query file
  query_file <- paste0("data/input/griis_belgium_", tolower(rank), "_base.txt")
  if(file.exists(query_file)){
    query <- gsub(pattern = "  ", replacement = "", paste0(readLines(query_file), collapse = " "))
  }else{
    warning(paste0(rank, " query file does not exist"))
    next #for testing purposes
  }
  
  # add nubkeys to query
  query <- gsub(
    pattern = "<--nubkeys-->", 
    replacement = paste(sprintf("'%s'", nubKey_list), collapse = ", "), 
    x = query
  )
  # add quotes to year
  query <- gsub(pattern = "year", replacement = "\"year\"", query)
  
  # export query
  writeLines(query, paste0("data/interim/cube_queries/griis_belgium_", tolower(rank), "_query.txt"))
}
```

```{r create class query, message=NA}
griis_class_keys <- griis_checklist %>% 
  group_by(classKey) %>%
  summarise(nubKey = first(nubKey))

classless <- griis_checklist %>% 
  filter(is.na(col_class_key)) %>% 
  select(nubKey) %>% 
  message(paste(" There are", nrow(.), "species without class"))

class_keys <- griis_checklist |> 
  filter(!is.na(col_class_key)) |> 
  distinct(col_class_key) |> 
  pull()

# get class base query
class_query <- gsub(pattern = "  ", replacement = "", paste0(readLines("data/input/belgium_class_base.txt"), collapse = " "))

# add class keys to query
class_query <- gsub(
  pattern = "<--nubkeys-->", 
  replacement = paste(sprintf("'%s'", class_keys), collapse = ", "), 
  x = class_query
)

# add quotes to year
class_query <- gsub(pattern = "year", replacement = "\"year\"", class_query)

# export query
writeLines(class_query, "data/interim/cube_queries/belgium_class_query.txt")
```

