---
title: 5831060
output: html_fragment
params:
  language: "en"
---
<style>
h1.title {
  display: none;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r sharedinfo, echo=FALSE}
VBP_link <- "https://natuurdata.inbo.be/bie-hub/species/5831060"
VBP_link_en <- "https://natuurdata.inbo.be/bie-hub/species/5831060?lang=en"
faunabeheer_link <- "https://faunabeheer.inbo.be/5831060"
style_str<-"font-size: 1.5em; font-style: italic;"
image_link<-"../Pictures/"
copyright_font<-"font-size: 0.8em;"
width="400"
height="267"
```


```{r nl_chunk, eval = params$language == "nl", results = "asis", echo=FALSE }
cat(paste0("
## <i>Crepis foetida rhoeadifolia</i>

<span style=\"", style_str, "\">Crepis foetida rhoeadifolia</span>
<br>


<br>

#### **Nuttige links** <br>
<p>Meer informatie over <i>Crepis foetida rhoeadifolia</i> kunt u vinden op het Vlaams Biodiversiteitsportaal.<br>
**Meer informatie: <a href=\"", VBP_link, "\"target=\"_blank\">Vlaams Biodiversiteitportaal</a>**

<p>
<br>
<br>
"))
```

```{r en_chunk, eval = params$language == "en", results = "asis", echo=FALSE }
cat(paste0("
## <i>Crepis foetida rhoeadifolia</i>

<span style=\"", style_str, "\">Crepis foetida rhoeadifolia</span>


<br>

#### **Useful links** <br>
<p>You can find more information about <i>Crepis foetida rhoeadifolia</i> on the Flemish Biodiversity Portal.<br>
**More information: <a href=\"", VBP_link_en, "\"target=\"_blank\">Flemish Biodiversity Portal</a>**

<p>
<br>
<br>
"))
```

```{r fr_chunk, eval = params$language == "fr", results = "asis", echo=FALSE }
cat(paste0("
## Crépide hérissé

<span style=\"", style_str, "\">Crepis foetida rhoeadifolia</span>


<br>

#### **Liens utiles** <br>
<p>Vous pouvez trouver plus d'informations sur crépide hérissé sur le portal biodiversité flamande (notez que ces informations sont actuellement disponible uniquement en néerlandais).<br>
**Plus d'informations: <a href=\"", VBP_link, "\"target=\"_blank\">portal biodiversité flamande</a>**

<p>
<br>
<br>
"))
```
