name: Copy S3 UAT to PROD
on:
  workflow_dispatch:

jobs:
  copy_s3:
    name: Copy S3 UAT to PROD
    environment: PROD
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Copy S3 UAT to PROD
        run: |
          aws s3 sync s3://inbo-exotenportaal-uat-eu-west-1-default/ s3://inbo-exotenportaal-prod-eu-west-1-default/
