name: Copy S3 UAT to PROD
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  copy_s3:
    name: Copy S3 UAT to PROD
    environment: PROD
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@517a711dbcd0e402f90c77e7e2f81e849156e31d # v6
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Copy S3 UAT to PROD
        run: |
          aws s3 sync s3://inbo-exotenportaal-uat-eu-west-1-default/ s3://inbo-exotenportaal-prod-eu-west-1-default/
