on:
  push: 
   branches:
    - "2-write-first-batch-of-automation-scripts"

  
name: test_griis

jobs:
  fetch-data:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_TOKEN: ${{ secrets.AUTOMATISATION }}
      gbif_user: ${{ secrets.GBIF_USER }}
      email: ${{ secrets.GBIF_EMAIL }}
      gbif_pwd: ${{ secrets.GBIF_PWD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.AUTOMATISATION }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install linux libraries
        run: |
          sudo apt install libsodium-dev
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libgdal-dev libproj-dev
          sudo apt install libudunits2-dev

      - name: Install R packages
        run: |
          source("src/install_packages_get_griis.R")
        shell: Rscript {0}
        
      - name: test_griis_status
        run: |
          source("src/test_griis_status.R")
        shell: Rscript {0}