on:
  schedule: 
   - cron: '0 0 1 1-12 *' #At 00:00 on day-of-month 1 in every month from January through December.
  workflow_dispatch:
  
name: update Xenopus laevis management

jobs:
  fetch-data:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_TOKEN: ${{ secrets.AUTOMATISATION }}
      amiabot: ${{ secrets.amiabot }}
      gsheet_token: ${{ secrets.gsheet_token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.AUTOMATISATION }}

      - name: Setup R
        uses: r-lib/actions/setup-r@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2

   
      - name: Install linux libraries
        run: |
          sudo apt update
          sudo apt install -y \
          libsodium-dev \
          libcurl4-openssl-dev \
          libgdal-dev \
          libproj-dev \
          libudunits2-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libharfbuzz-dev \
          libfribidi-dev \
          libpng-dev \
          libuv1-dev

      - name: Install R packages
        run: |
          source("src/Xenopus laevis management/install_packages_Xenopus_laevis_management.R")
        shell: Rscript {0}
        
      - name: Xenopus laevis management
        run: |
          source("src/Xenopus laevis management/run_Xenopus_laevis_management.R")
        shell: Rscript {0}

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@fc0511fd56cf2eb2631a9601dbc45299de406564 # v0.11.1
        with:
          github_token: ${{ secrets.AUTOMATISATION }}
          commit_prefix: "[AUTO]"
          commit_message: "run Xenopus laevis management"
          target_branch: automatic-xenopus-laevis-management
          
      - name: Get branch name
        run: |
          git branch --show-current

      - name: Create pull request
        uses: devops-infra/action-pull-request@3f1cdfa7c7976f6302e820e2b391e846d933693c # v0.4.2
        with:
          github_token: ${{ secrets.AUTOMATISATION }}
          target_branch: uat
          title: "[AUTO] update Xenopus laevis management"
          template: .github/PR_Xenopus_laevis_management.md
          reviewer: SanderDevisscher, maudsegal, soriadelva
          label: automated workflow
          get_diff: false
